name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'

defaults:
  run:
    working-directory: starter/backend

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Run flake8 Lint
      uses: py-actions/flake8@v2
      with:
        max-line-length: "120"

  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Run testing jobs
      run: pipenv run test
      continue-on-error: false

  run-build:
    needs: [run-lint, run-test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Run testing jobs
      run: pipenv run test
      continue-on-error: false

    - name: Build Docker image
      run: docker build -t be-movies-picture .